### ISSUE TITLE
Error starting web application

### ISSUE THREAD

**Issue by Diego-Pino** [Darkensses/sofifa-psx-react#9]
**Error starting web application**

he **Phusion Passenger** application server tried to start the web application through a Passenger-internal helper tool called the "wrapper". But Passenger was unable to execute that helper tool because it encountered an internal error.

The stdout/stderr output of the subprocess so far is:

**SyntaxError: Unexpected identifier**
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at Module.require (/opt/passenger-5.3.7-9.el7.cloudlinux/src/helper-scripts/node-loader.js:80:25)
    at require (internal/modules/cjs/helpers.js:25:18)
    at loadApplication (/opt/passenger-5.3.7-9.el7.cloudlinux/src/helper-scripts/node-loader.js:243:2)
    at setupEnvironment (/opt/passenger-5.3.7-9.el7.cloudlinux/src/helper-scripts/node-loader.js:214:2)

![Image](https://i.ibb.co/kQRgsHN/error-starting-web-app.png)

returncode: 0
stdout:
> we-mcr@0.0.1 build /home/web
> react-scripts build

Creating an optimized production build...
Compiled with warnings.

**./src/components/Editor/index.js**
  Line 3:20:  'Radio' is defined but never used          no-unused-vars
  Line 3:27:  'RadioGroup' is defined but never used     no-unused-vars
  Line 3:39:  'useRadioState' is defined but never used  no-unused-vars

**./src/api/coreMCR.js**
  Line 3:7:     'contentType' is assigned a value but never used  no-unused-vars
  Line 44:7:    'off_age' is assigned a value but never used      no-unused-vars
  Line 47:7:    'off_acce' is assigned a value but never used     no-unused-vars
  Line 67:7:    'power' is assigned a value but never used        no-unused-vars
  Line 71:7:    'velocity' is assigned a value but never used     no-unused-vars
  Line 74:7:    'head' is assigned a value but never used         no-unused-vars
  Line 656:45:  'acc' is assigned to itself                       no-self-assign
  Line 657:45:  'acc' is assigned to itself                       no-self-assign

**Comment by Darkensses** [comment]
El error corresponder al servicio que tiene para deployar. Desconozco como solucionarlo :( 

fix planead en ./src/components/Editor/index.js

el otro warning (./src/api/coreMCR.js) lo corregiré hasta asegurarme que esas variables no se usan, ya que es parte del script original de la macro de polipoli.
